import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service · Conference Team Skills",
  description:
    "The Conference Team Skills are open source under the MIT license. By using them you agree to the terms below.",
};

export default function TermsPage() {
  return (
    <main className="legal-page">
      <div className="nav">
        <Link href="/">← Back to landing page</Link>
      </div>
      <h1 className="display">Terms of Service</h1>
      <p className="lede">
        The Conference Team Skills are open source under the MIT license. By using them you agree to the terms below.
      </p>
      <p className="meta">Last updated: April 28, 2026 · v1.0.4</p>

      <h2>1. License — MIT</h2>
      <p>
        The skills, scripts, documentation, and design assets in this repository are released under the MIT License. The full text is in{" "}
        <a href="https://github.com/msg2ai/conference-team-skills/blob/main/LICENSE">LICENSE</a>. In plain language: you can use, copy, modify, distribute, and sell — including for commercial events — provided you keep the copyright notice intact. Attribution is appreciated but not required.
      </p>

      <h2>2. The skills are tools — you remain responsible for the output</h2>
      <p>
        The skills are sets of instructions that run inside Claude. The actual writing, planning, and decisions come from Claude (an AI assistant made by Anthropic), shaped by what you type. The output is a draft. Always review it before sending it, signing it, paying for it, publishing it, or making decisions based on it. You are responsible for what you do with the output.
      </p>

      <div className="legal-block">
        <strong>Critical examples.</strong> If a skill drafts a sponsor contract — have a lawyer review it. If a skill drafts a budget — have your accountant review it. If a skill drafts a press release — verify the facts. If a skill drafts an outreach email and connects it to a tool like Gmail — confirm the recipient list before sending.
      </div>

      <h2>3. No warranty</h2>
      <p>
        The skills are provided &ldquo;as is&rdquo;, without warranty of any kind, express or implied — including (but not limited to) warranties of merchantability, fitness for a particular purpose, accuracy, completeness, or non-infringement. To the maximum extent permitted by applicable law, MSG2AI and contributors disclaim all liability for any damages, losses, or costs of any kind arising out of your use of the skills.
      </p>

      <h2>4. Third-party services</h2>
      <p>
        The skills are designed to work with third-party services — Claude (Anthropic), Google Drive, Gmail, Google Calendar, Dropbox, Notion, Vercel, GitHub, Stripe, Firecrawl, Canva, Zoom, Twenty CRM, ClickUp, Asana, Obsidian, AgentMail, AI Ambassador, ActionNotes, and others. Your use of those services is governed by their own terms and privacy policies. We do not control them and are not responsible for their behavior or availability.
      </p>

      <h2>5. Acceptable use</h2>
      <p>
        You agree not to use the skills (or anything generated by them) for: anything illegal in your jurisdiction; impersonating anyone; spam or unsolicited commercial messaging at scale; building scams; harassment or harm; processing personal data of others without an appropriate legal basis. You also agree to comply with the terms of any third-party services you connect.
      </p>

      <h2>6. Trademarks</h2>
      <p>
        &ldquo;Claude&rdquo; is a trademark of Anthropic. &ldquo;MSG2AI&rdquo;, &ldquo;AI Ambassador&rdquo;, and &ldquo;ActionNotes&rdquo; are trademarks of MSG2AI. All other trademarks belong to their respective owners. The MIT license does not grant you any rights to use these names beyond fair, descriptive use.
      </p>

      <h2>7. Changes to these terms</h2>
      <p>
        We may update these terms by editing this page in the public repository. The version stamp at the top reflects the current revision; the git history holds every previous version.
      </p>

      <h2>8. Governing law</h2>
      <p>
        To the extent permitted by applicable law, any dispute relating to these terms is governed by the laws of the jurisdiction in which MSG2AI is incorporated, without regard to conflict-of-law principles.
      </p>

      <h2>9. Contact</h2>
      <p>
        Questions or notices: <a href="mailto:info@msg2ai.xyz">info@msg2ai.xyz</a>.
      </p>
    </main>
  );
}
